json.extract! course, 
    :id, 
    :title, 
    :description, 
    :price, 
    :duration, 
    :instructor, 
    :course_description, 
    :what_youll_learn,
    :requirements, 
    :num_lectures, 
    :num_videos, 
    :num_students,
    :num_reviews,
    :who_this_course_is_for